DEL /F /S /Q /AH "*.suo"
DEL /F /S /Q "*.sdf"
DEL /F /S /Q "*.opensdf"
DEL /F /S /Q "*.db"
RMDIR /S /Q "RandomLibraryUnitTest\Debug"
RMDIR /S /Q "RandomLibraryUnitTest\Release"
RMDIR /S /Q "Debug"
RMDIR /S /Q "Release"
RMDIR /S /Q "ipch"
RMDIR /S /Q ".vs"